name: CD workflow

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    name: Run linting
    steps:
      - uses: actions/checkout@v5
      - name: Login docker
        run: docker login -u ${{vars.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker
        run: docker build . -t chuotcona123/training:${{ github.sha }}

      - name: Echo docker
        run: docker image list
