name: CI workflow

on:
  pull_request:
    branches:
      - main
      - dev

env:
  NODE_ENV: 22.0.0

jobs:
  unit-test:
    runs-on: ubuntu-latest
    name: Run Unit Test
    steps:
      - name: Run tests
        uses: ./.github/workflows/test_workflow.yml
