# .github/workflows/ci.yml

name: CI workflow

on:
  pull_request:
    branches:
      - main
      - dev

env:
  NODE_ENV: 22.0.0

jobs:
  unit-test:
    # ðŸŒŸ THAY THáº¾ TOÃ€N Bá»˜ Cáº¤U HÃŒNH JOB NÃ€Y Báº°NG Lá»œI Gá»ŒI WORKFLOW
    uses: ./.github/workflows/test_workflow.yml # CÃº phÃ¡p Ä‘Ãºng, Ä‘áº·t trá»±c tiáº¿p dÆ°á»›i job_id
    # LÆ°u Ã½: job nÃ y sáº½ sá»­ dá»¥ng runs-on vÃ  cÃ¡c cáº¥u hÃ¬nh khÃ¡c tá»« test_workflow.yml
